### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by Zengfanxu1111** [InternLM/xtuner#273] opened 2023-12-20 11:03 UTC
It accured when  I merged model.
I used command:   <xtuner convert merge ./chatglm-6b-base/models--THUDM--chatglm3-6b-base/snapshots/f91a1de587fdc692073367198e65369669a0b49d  checkpoint-hf  combined-model>

The directory structure is as shown in the picture.
![QQ截图20231220190231](https://github.com/InternLM/xtuner/assets/39284193/f746cfa4-93e4-40ea-8ede-6abef07db46e)

**Comment by LZHgrla** [comment] 2023-12-20 11:06
@Zengfanxu1111 
Hi!
Could you please post the full log messages?

**Comment by Zengfanxu1111** [comment] 2023-12-20 11:09
Sure!
"""
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\tools\model_converters\merge.py", line 60, in <module>
    main()
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\xtuner\tools\model_converters\merge.py", line 53, in main
    model_merged.save_pretrained(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\transformers\modeling_utils.py", line 2376, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 475, in _flatten
    return {
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 404, in _tobytes
    tensor = tensor.to("cpu")
NotImplementedError: Cannot copy out of meta tensor; no data!

"""

**Comment by LZHgrla** [comment] 2023-12-20 11:19
@Zengfanxu1111 
Please try to use this script for merging
```
python SCRIPT.py ./chatglm-6b-base/models--THUDM--chatglm3-6b-base/snapshots/f91a1de587fdc692073367198e65369669a0b49d checkpoint-hf combined-model
```
```python
# Copyright (c) OpenMMLab. All rights reserved.
import argparse

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer


def parse_args():
    parser = argparse.ArgumentParser(
        description='Merge a HuggingFace adapter to LLM')
    parser.add_argument('model_name_or_path', help='model name or path')
    parser.add_argument('adapter_name_or_path', help='adapter name or path')
    parser.add_argument(
        'save_dir', help='the directory to save the merged model')
    parser.add_argument(
        '--max-shard-size',
        type=str,
        default='2GB',
        help='Only applicable for LLM. The maximum size for '
        'each sharded checkpoint.')
    parser.add_argument(
        '--offload-folder',
        default=None,
        help='The folder in which to offload the model weights (or where '
        'the model weights are already offloaded).')
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    model = AutoModelForCausalLM.from_pretrained(
        args.model_name_or_path,
        torch_dtype=torch.float16,
        low_cpu_mem_usage=True,
        device_map='auto',
        offload_folder=args.offload_folder,
        trust_remote_code=True,
        empty_init=False)
    tokenizer = AutoTokenizer.from_pretrained(
        args.model_name_or_path,
        trust_remote_code=True,
        encode_special_tokens=True)
    model_unmerged = PeftModel.from_pretrained(
        model,
        args.adapter_name_or_path,
        device_map='auto',
        torch_dtype=torch.float16,
        offload_folder=args.offload_folder,
        is_trainable=False)
    model_merged = model_unmerged.merge_and_unload()
    print(f'Saving to {args.save_dir}...')
    model_merged.save_pretrained(
        args.save_dir, max_shard_size=args.max_shard_size)
    tokenizer.save_pretrained(args.save_dir)
    print('All done!')


if __name__ == '__main__':
    main()

```

**Comment by Zengfanxu1111** [comment] 2023-12-20 11:21
I m sorry that it still have the same error like follows:
'''
Traceback (most recent call last):
  File "E:\pythonworkspace\ChatGLM-6B\SCRIPT.py", line 61, in <module>
    main()
  File "E:\pythonworkspace\ChatGLM-6B\SCRIPT.py", line 54, in main
    model_merged.save_pretrained(
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\transformers\modeling_utils.py", line 2376, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 281, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 475, in _flatten
    return {
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 479, in <dictcomp>
    "data": _tobytes(v, k),
  File "C:\ProgramData\anaconda3\envs\chatglm_env\lib\site-packages\safetensors\torch.py", line 404, in _tobytes
    tensor = tensor.to("cpu")
NotImplementedError: Cannot copy out of meta tensor; no data!

'''

**Comment by LZHgrla** [comment] 2023-12-20 11:23
Ok, thanks!
It seems that there is a bug on some other parts, and I will try to fix it.

**Comment by Zengfanxu1111** [comment] 2023-12-20 11:25
It's okay, I am honored to help you find out the issue. If it gets resolved, I would appreciate it if you could respond to me. Thank you very much!

**Comment by LZHgrla** [comment] 2023-12-20 11:34
Everything works well in my env..
```
transformers==4.36.2
peft==0.7.1
```

Could you please post the version of this two lib?
```
pip list | grep transformers
pip list | grep peft
```

**Comment by Zengfanxu1111** [comment] 2023-12-20 11:39
here is the message:
(chatglm_env) E:\pythonworkspace\ChatGLM-6B>pip list | findstr torch
torch                         2.0.0+cu117
torchaudio                    2.0.1+cu117
torchvision                   0.15.1+cu117

(chatglm_env) E:\pythonworkspace\ChatGLM-6B>pip list | findstr transformers
transformers                  4.36.2
transformers-stream-generator 0.0.4

(chatglm_env) E:\pythonworkspace\ChatGLM-6B>pip list | findstr peft        
peft                          0.7.1

**Comment by LZHgrla** [comment] 2023-12-20 12:57
Sorry, I cannot reproduce this bug with the same libs' version

One possible solution is to set `low_cpu_mem_usage=False` for `AutoModelForCausalLM.from_pretrained`

**Comment by lvhan028** [comment] 2023-12-20 13:27
@LZHgrla lmdeploy lite module met a similar issue. It is resolved in  https://github.com/InternLM/lmdeploy/pull/848

**Comment by LZHgrla** [comment] 2023-12-20 13:28
> @LZHgrla lmdeploy lite module met a similar issue. It is resolved in [InternLM/lmdeploy#848](https://github.com/InternLM/lmdeploy/pull/848)

thanks!

**Comment by Zengfanxu1111** [comment] 2023-12-20 13:55
> Sorry, I cannot reproduce this bug with the same libs' version
> 
> One possible solution is to set `low_cpu_mem_usage=False` for `AutoModelForCausalLM.from_pretrained`

thank you I solved by this! At the same time, it is important to note not to pass the 'device_map' parameter.

**Comment by pppppM** [comment] 2023-12-21 01:54
@LZHgrla @Zengfanxu1111 There might be some issues with the `device_map` in `transfomers`. 

With the same `device_map`, parameters can be correctly loaded via the `load_checkpoint` interface of `accelerate`. However, if loaded through `from_pretrained`, it would generate meta tensors. 

My solution in `lmdeploy` is not to use `device_map`.

**Comment by chinaphilip** [comment] 2023-12-23 08:32
I set device_map="cpu" and low_cpu_mem_usage=True, using the follow scirpt, it worked

> @Zengfanxu1111 Please try to use this script for merging. I passed `empty_init=False` to `AutoModelForCausalLM`
> 
> ```
> python SCRIPT.py ./chatglm-6b-base/models--THUDM--chatglm3-6b-base/snapshots/f91a1de587fdc692073367198e65369669a0b49d checkpoint-hf combined-model
> ```
> 
> ```python
> # Copyright (c) OpenMMLab. All rights reserved.
> import argparse
> 
> import torch
> from peft import PeftModel
> from transformers import AutoModelForCausalLM, AutoTokenizer
> 
> 
> def parse_args():
>     parser = argparse.ArgumentParser(
>         description='Merge a HuggingFace adapter to LLM')
>     parser.add_argument('model_name_or_path', help='model name or path')
>     parser.add_argument('adapter_name_or_path', help='adapter name or path')
>     parser.add_argument(
>         'save_dir', help='the directory to save the merged model')
>     parser.add_argument(
>         '--max-shard-size',
>         type=str,
>         default='2GB',
>         help='Only applicable for LLM. The maximum size for '
>         'each sharded checkpoint.')
>     parser.add_argument(
>         '--offload-folder',
>         default=None,
>         help='The folder in which to offload the model weights (or where '
>         'the model weights are already offloaded).')
>     args = parser.parse_args()
>     return args
> 
> 
> def main():
>     args = parse_args()
>     model = AutoModelForCausalLM.from_pretrained(
>         args.model_name_or_path,
>         torch_dtype=torch.float16,
>         low_cpu_mem_usage=True,
>         device_map='auto',
>         offload_folder=args.offload_folder,
>         trust_remote_code=True,
>         empty_init=False)
>     tokenizer = AutoTokenizer.from_pretrained(
>         args.model_name_or_path,
>         trust_remote_code=True,
>         encode_special_tokens=True)
>     model_unmerged = PeftModel.from_pretrained(
>         model,
>         args.adapter_name_or_path,
>         device_map='auto',
>         torch_dtype=torch.float16,
>         offload_folder=args.offload_folder,
>         is_trainable=False)
>     model_merged = model_unmerged.merge_and_unload()
>     print(f'Saving to {args.save_dir}...')
>     model_merged.save_pretrained(
>         args.save_dir, max_shard_size=args.max_shard_size)
>     tokenizer.save_pretrained(args.save_dir)
>     print('All done!')
> 
> 
> if __name__ == '__main__':
>     main()
> ```

**Comment by LZHgrla** [comment] 2023-12-26 10:02
Hi, @Zengfanxu1111 
The latest xtuner (version 0.1.11) has fixed this bug

Please try to update the xtuner, with `pip install -U xtuner`

**Closed** 2023-12-29 04:14 UTC
